### PR TITLE
Create img

### PR DESCRIPTION
**Pull request by 73dward5**
a container for images

### CODE REVIEW

**Comment by tobywhughes** [comment]
What is this?

**Comment by 73dward5** [comment]
a folder to hold any images we use

**Comment by tobywhughes** [comment]
Oh I see. Github didn't make that clear. merged.

**Comment by 73dward5** [comment]
That did not create a folder. Could you make a dir called img?

**Comment by tobywhughes** [comment]
Ya, I realized that. I'll fix it.

**Pull request merged**
